---
title: "Ethica_utilities"
author: "A.T. du Toit"
date: "`r Sys.Date()`"
output: html_document
---

```{r To do lists}
# ** DONE 
# [x ] write function(s) to format answer columns as the correct type (numeric, character, etc)
# [x ] make 'deprecated' script and move old code into that 
# [x ] upgrade function to join data frames so that it does not require their names to be specified! 

# [x ] where possible use vectors in str_remove() instead of repeated calls 
# [x ] change "id" in combined_df to "obs_id"
# [x ] move all patterns into one initial block and annotate what they are used for 
#   [x ] fix pattern numbering
# [x ] add activity or survey numbers at the start of column names 
# [x ] use repeated() in line 82f. 
# [x ] Fix naming of MAQ questions 
#   [x ] insert "opt" in from of MAQ option col option numbers 
# [x ] Function to extract data frames from list 
# [x ] Function to join data frames into one 
# [x] reorganise combined_df by adding a select() call or similar. Perhaps save vectors of variable names earlier on and use them inside the select() call. Put everything() at the end to ensure _all_ variables are included. 
# [x ] check and fix location of obs.id - actually obs_id .. ?? 
# [x] put in an obs id at individual qre and combined df levels  
# [x] evaluate if I need the MAQ processing code - may have been superceded by what Avicenna now provides- done, the MAQ code is no longer necessary  
# [x ] find complete list of 3-character activity extensions in Avicenna docs 
      # SAQ: Single Answer
      # MAQ: Multiple Answer
      # AUT: Audio/Text
      # IMG: Image
      # AUD: Audio
      # VID: Video
      # VAS: Visual Analog Scale
      # MAS: Mass
      # LEN: Length
      # BAR: Barcode
      # CAL: Calendar
      # NUM: Number
      # FFT: Text / Information
# [x ] check for dependencies between objects generated in this workflow and in the source functions - there should not be any, so eliminate any that I find -- AFAICT there weren't any 
# [x ] Split this into a source file with funs and patterns and a workflow file (ie the remainder of this one)
# [x ] change titles on code chunks to reflect what they actually do! 


# ** Still to do 
# [ip] Clarify survey and activity numbers with Amin or Mohammad and alter naming conventions accordingly 
# [ip] change variable names to agree with Avicenna's new naming scheme (Study / Activity / Survey) 

# [  ] related to metadata: look at https://learn.avicennaresearch.com/reference/survey/view-responses#survey-data-structure to see Question Type ID q_type_id, which encodes question type (_SAQ, etc) information 
# [  ] check for source functions' dependencies upon objects generated by other source functions - what to do about these? 
#       - initial thought: generate all needed objects in one go (maybe yet another function) at the start. "This function generates all of the objects required by the other functions in this package." Use "_setup" in fun name. 
# [  ] (later) move these to-do and done lists to a separate file 
# [  ] Resolve: combined_df function implicitly assumes that all of the data frames in df_list have the same research participant IDs, or at least that they are meant to all have the same IDs (if not it's assumed to be a missing data problem); do I need to do anything about this? 
# [  ] Resolve: Do I need different functions for one-off questionnaires vs EMAs? 
# [  ] 


# ** _Possible_ to do's (not sure yet)
# [  ] ? make generic col names shorter 
# [ip] ? consider a study metadata df (or list) as another output of the suggested workflow. 
#       This could include a data dictionary and labels - but look at this first:
#       https://learn.avicennaresearch.com/how-to/activities/online-surveys-documentation-made-easy-with-avicenna
#       because it may have already been done 
#       # [  ] ? add functions to create variable labels .. maybe. later, (not first release) 
#       - have a classes_and_types df now
# [  ] ? add an obs.all col which gives the ordinal # across _all_ observations, not just within one activity. 


# Versions
#           0.3:  most functions moved across to source file
#                 one or two chunks at end, titled ## Moved to source file, deleted 
#                 remainder of deprecated code at bottom moved over to 'deprecated.R' file 
#                 made functions to create a combined df and to extract individual data frames from df_list 
#                 renamed some chunks with more informative names 

```

```{r Frontmatter and instructions and notes}
# This script processes CSV files as output from Avicenna/Ethica. 
# To use this script with your data files: 
#   - the files must be in CSV format. 
#   - change the file path in "Define names and constants" to point at the folder with your data files. 
# The script will output a dataframe for each CSV file; dataframes will be named xxx Survey.Number_df. The dataframe will have clean numerical output for single-answer questions, and also will have all variables renamed as Survey.Number_Question.Number_Question.Type. 
# If you want a CSV file outputted as well, you may un-comment the write.csv() call at the end of this file and add in the appropriate file path. 

```

```{r load libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Load libraries ----
library(rebus)
library(tidyverse)      # edit to include only the individual packages needed
library(magrittr)
library(knitr)
library(conflicted)

```

```{r set preferences}
conflicts_prefer(rebus::alpha(), dplyr::select())   
```

## Define names and constants
```{r Create: define variables and constants needed for *current* workflow}
# NB backslashes must be changed into forward slashes   # [ ] make or find a wee function to do this   
data_path <- "C:/Users/atdut/OneDrive - Western Sydney University/PhD/Rwork/ethica_utilities/data_files_json"

```

```{r Create: read in code with functions and constants from source file}
source("Ethica_utilities_source.R")   

```

## Functions for file naming and variable renaming    
```{r Create: import CSVs and create dfs using a regular naming scheme, warning=FALSE, message=FALSE}
import_CSV() 

```

```{r Fix:    run functions to clean col names and remove unwanted answer cols}
clean_all_names()

remove_answ_cols()

```

```{r Fix:    overwrite SAQ answer columns with numberic answer code}
extract_saq_numbers()

```

```{r Fix:    rename answer columns using regular naming scheme}
rename_answ_cols()   
```

```{r Fix:    add a column with number of missing values in that row}
add_all_msg_cols()   

```

```{r Create: add columns with the ordinal number of each observation}
add_all_obs.no_cols()   

```

```{r Fix:    change some variable classes}
change_some_classes()

```

```{r Create: join data frames in df_list into one data frame}
create_combined_df()
```

```{r Create: extract individual data frames from df_list}
extract_all_df()  

```

************** STOP HERE ************

```{r end knit}
knitr::knit_exit()   

```

```{r tidy up 1}
# rm()

```

```{r Create: write CSV files if required}
# # Un-comment and add file path if a CSV file is required. NB Keep this function call at the end of the script.  
# # write.csv(pathways_df, file = "C:/your/file/path/something/like/output_files/your_filename.csv")   

```

## Checks    
```{r checks of length for rename answer columns chunk, eval=FALSE}
length(column_names)
length(logV)
length(raw_question_numbers_int)
length(raw_question_numbers)
length(question_type_int)
length(question_type)
length(maqV)
length(maq_option_no)
length(question_numbers)

```

```{r checks for rename answer columns chunk, eval=FALSE}
# inspect intermediate objects
column_names # not useful as overwritten
logV
raw_question_numbers_int
raw_question_numbers
question_type_int
question_type
maqV
maq_option_no
question_numbers
```

```{r Check:  classes and types, eval=FALSE}
all_classes <- sapply(combined_df, class) %>% data.frame() %>% t() %>% data.frame() %>% rename(class1=1, class2=2)
all_types <- as.list(sapply(combined_df, typeof)) %>% data.frame() %>% t() %>% data.frame() %>% rename(type=1)
classes_and_types <- cbind(all_classes, all_types)
rm(all_classes, all_types)

classes_and_types %>% mk     

```


## Deprecated    
