---
title: "Ethica_utilities"
author: "A.T. du Toit"
date: "`r Sys.Date()`"
output: html_document
---

```{r To do lists}
# DONE 
# [x ] write function(s) to format answer columns as the correct type (numeric, character, etc)
# [x ] make 'deprecated' script and move old code into that 
# [x ] upgrade function to join data frames so that it does not require their names to be specified! 

# [x ] where possible use vectors in str_remove() instead of repeated calls 
# [x ] change "id" in combined_df to "obs_id"
# [x ] move all patterns into one initial block and annotate what they are used for 
#   [x ] fix pattern numbering
# [x ] add activity or survey numbers at the start of column names 
# [x ] use repeated() in line 82f. 
# [x ] Fix naming of MAQ questions 
#   [x ] insert "opt" in from of MAQ option col option numbers 
# [x ] Function to extract data frames from list 
# [x ] Function to join data frames into one 
# [x] reorganise combined_df by adding a select() call or similar. Perhaps save vectors of variable names earlier on and use them inside the select() call. Put everything() at the end to ensure _all_ variables are included. 
# [x ] check and fix location of obs.id - actually obs_id .. ?? 
# [x] put in an obs id at individual qre and combined df levels  
# [x] evaluate if I need the MAQ processing code - may have been superceded by what Avicenna now provides- done, the MAQ code is no longer necessary  

# Still to do 
# [ip] Clarify survey and activity numbers with Amin or Mohammad and alter naming conventions accordingly 
# [ip] change variable names to agree with Avicenna's new naming scheme (Study / Activity / Survey) 
# [  ] ? make generic col names shorter 
# [  ] ? add an obs.all col which gives the ordinal # across _all_ observations, not just within one activity. 
# [ip] ? consider a study metadata df (or list) as another output of the suggested workflow. 
#       This could include a data dictionary and labels - but look at this first:
#       https://learn.avicennaresearch.com/how-to/activities/online-surveys-documentation-made-easy-with-avicenna
#       because it may have already been done 
#       # [  ] ? add functions to create variable labels .. maybe. later, (not first release) 
#       - have a classes_and_types df now

# [x ] find complete list of 3-character activity extensions in Avicenna docs 
      # SAQ: Single Answer
      # MAQ: Multiple Answer
      # AUT: Audio/Text
      # IMG: Image
      # AUD: Audio
      # VID: Video
      # VAS: Visual Analog Scale
      # MAS: Mass
      # LEN: Length
      # BAR: Barcode
      # CAL: Calendar
      # NUM: Number
      # FFT: Text / Information
# [  ] related: llok at https://learn.avicennaresearch.com/reference/survey/view-responses#survey-data-structure to see Question Type ID q_type_id, which encodes this information 
# 
# [ip] Split this into a source file with funs and patterns and a workflow file (ie the remainder of this one)
#       [  ] decide what is a function and what is part of the rest of the workflow 
# [  ] change titles on code chunks to reflect what they actually do! 

```

```{r Frontmatter and instructions and notes}
# This script processes CSV files as output from Avicenna/Ethica. 
# To use this script with your data files: 
#   - the files must be in CSV format. 
#   - change the file path in "Define names and constants" to point at the folder with your data files. 
# The script will output a dataframe for each CSV file; dataframes will be named xxx Survey.Number_df. The dataframe will have clean numerical output for single-answer questions, and also will have all variables renamed as Survey.Number_Question.Number_Question.Type. 
# If you want a CSV file outputted as well, you may un-comment the write.csv() call at the end of this file and add in the appropriate file path. 

```

```{r load libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Load libraries ----
library(rebus)
library(tidyverse)      # edit to include only the individual packages needed
library(magrittr)
library(knitr)
library(conflicted)

```

```{r set preferences}
conflicts_prefer(rebus::alpha(), dplyr::select())   
```

## Define names and constants
```{r Create: Define variables and constants needed for current workflow}
# NB backslashes must be changed into forward slashes   # [ ] make or find a wee function to do this   
data_path <- "C:/Users/atdut/OneDrive - Western Sydney University/PhD/Rwork/ethica_utilities/data_files_json"

```

```{r Create: read in code with functions and constants from source file}
source("Ethica_utilities_source.R")   

```

## Functions for file naming and variable renaming    
```{r Create: functions for data frame naming, warning=FALSE, message=FALSE}
import_CSV <<- function() {
  # Load and rename CSV files 
  file_names <<- Sys.glob(paste0(data_path, "/*.csv"))
  
  # Set up empty objects 
  df_names <<- data.frame()
  activity_numbers <<- vector()
  df_list <<- list()
  
  # extract study number
  study_number <<- str_extract(file_names[1], pattern = pattern1)
  study_number <<- study_number %>% str_remove_all("activity_response_")
  
  # Create data frame names from file_names and read in data from CSV files 
  i <- 0   
  for (file_name in file_names) {
    i <- i + 1
  # extract activity number
  activity_numbers[i] <<- str_extract(file_name, pattern = pattern3 )
  activity_numbers[i] <<- activity_numbers[i] %>% str_remove_all(pattern3.1) %>% str_remove_all("_")
  
  # Generate df names from CSV file names
  df_name <<- paste0("S", study_number, "_", activity_numbers[i], "_df", collapse = NULL)
  
  df_names <<- c(df_names, df_name)
  df_names <<- as.vector(df_names, mode = "character")
  
  # read in CSV files   
  df_list[[df_name]] <<- read_csv(file_name, col_names = TRUE, na = c("", "NA"))
  
  # how to make all these objects available in the env ?
  # return(list(obj1, obj2))
      }
  }

```

```{r run the new fun from above chunk, warning=FALSE, message=FALSE}
import_CSV() 

```

```{r Create:   functions to clean column names, detect and remove columns with answer labels}
clean_all_names <<- function() {
  for (df_name in df_names)  {
    df_list[[df_name]] <<- df_list[[df_name]] %>% janitor::clean_names()
    }
  }
  
remove_answ_cols <<- function() {
  for (df_name in df_names)  {
    df_list[[df_name]] <<- df_list[[df_name]] %>% select(!matches(pattern2))
    df_list[[df_name]] <<- df_list[[df_name]] %>% select(!matches(pattern2.1))
    }
  }
```

```{r Fix:    run functions to clean col names, remove unwanted answer cols}
clean_all_names()

remove_answ_cols()

```


```{r Fix:    extract numeric answer codes and rewrite 'metadata' answer columns}
extract_saq_numbers <- function() {
  for (df_name in df_names)  {
    df_list[[df_name]] <<- df_list[[df_name]] %>% mutate(across(contains("_metadata_"), number_extract_single2))
    }
  }
```

```{r}
#  <<- df_list[[df_name]] %>% 
extract_saq_numbers()

```


```{r Fix:    rename answer columns}
rename_answ_cols <- function() {
  i <- 0
  for (df_name in df_names)  {
      i <- i + 1

  column_names <<- colnames(df_list[[df_name]])
  logV <<- str_detect(column_names, pattern = pattern5)
  activity_no <<- str_extract(df_name, pattern = pattern6) %>% str_remove_all("df") %>% str_remove_all("_")
  
  raw_question_numbers_int <<- str_extract(column_names[logV], pattern = pattern5)
  raw_question_numbers <<- str_extract(raw_question_numbers_int, pattern = pattern5.1)
  raw_question_numbers <<-  raw_question_numbers %>% str_remove("x")
  
  # extract 3 letter code for question type
  question_type_int <<- str_extract(column_names[logV], pattern = pattern7)    
  question_type <<- str_extract(question_type_int, pattern = pattern7.1)
  
  maqV <<- str_detect(column_names[logV], pattern = "_maq_")
  
  if (sum(maqV)>0) {
    maq_option_no <<- str_extract(column_names[logV], pattern =  pattern8) %>% str_remove("_maq") %>% str_remove("_") %>%  str_replace_na(replacement = "NA") %>% str_replace("NA", "") 
    maq_option_no <<- maq_option_no %>%  str_replace_all(capture(repeated(DGT,1,2)), "_opt" %R% REF1)
  question_numbers <<- str_c("a", activity_no, "_", "q", raw_question_numbers, "_", question_type, maq_option_no, sep = "")  
    }
  
  if (sum(maqV)==0) {
  question_numbers <<- str_c("a", activity_no, "_", "q", raw_question_numbers, "_", question_type, sep = "")  
    }
  
  column_names[logV] <<- question_numbers
  colnames(df_list[[df_name]]) <<- column_names   
    }   
  }
```

```{r Fix:  run rename_answ_cols fun}
rename_answ_cols()   
```


```{r create:  function to add a column with number of missing values in that row}
add_all_msg_cols <- function() {
  for (df_name in df_names)  {
    df_list[[df_name]] <<- df_list[[df_name]] %>% naniar::add_n_miss()  
   }
  }
```

```{r Fix:    run function to add a column with number of missing values in that row}
add_all_msg_cols()   

```


```{r create:  arrange by answer dttm and add a column with ordinal no of observation}
add_all_obs.no_cols <- function() {
  for (df_name in df_names)  {
    df_list[[df_name]] <<- df_list[[df_name]] %>% arrange(record_time)
    activity_no <<- str_extract(df_name, pattern = pattern6) %>% str_remove_all("df") %>% str_remove_all("_")
    new.var <<- paste("obs", activity_no, sep = "." )
    assign(new.var, 1:nrow(df_list[[df_name]]))
    df_list[[df_name]] <<- df_list[[df_name]] %>% mutate("obs.{activity_no}" := eval(sym(new.var)), .before = uuid)
    }
  }
```

```{r Fix:    }
add_all_obs.no_cols()   

```


```{r Create: function to change some var classes}
change_some_classes <- function() {
  for (df_name in df_names)  {
    df_list[[df_name]] <<- df_list[[df_name]] %>% select(all_of(sortvec), starts_with("obs."), everything())
  
    df_list[[df_name]] <<- df_list[[df_name]] %>% 
      mutate(participant_id = as.integer(participant_id)) %>%
      mutate(participant_status = as.integer(participant_status)) %>%
      mutate(status = as.integer(status)) %>%
      mutate(triggering_logic_id = as.integer(triggering_logic_id)) %>%
      mutate(triggering_logic_type = as.integer(triggering_logic_type))
    }
  }
```

```{r Fix:    run function to change some var classes}
change_some_classes()

```

```{r Create: functions for joining data frames in df_list into *one* data frame, eval=TRUE}
# This function will assume that all of the data frames in df_list have the same research participant IDs, or at least that they are meant to all have the same IDs (if not it's assumed to be a missing data problem)
# Do I need different functions for one-off questionnaires vs EMAs? 

# 2nd iteration   
combined_df <- bind_rows(df_list, .id = "original_df")   

combined_df %<>% select(all_of(sortvec), starts_with("obs."), everything()) %>%
  relocate(c(starts_with("obs"), original_df), .before = uuid)

```

```{r Create: extract data frames from list if needed}
list2env(df_list, .GlobalEnv)

```

************** STOP HERE ************

```{r end knit}
knitr::knit_exit()   

```

```{r tidy up 1}
# rm()

```

```{r Create: write CSV files if required}
# # Un-comment and add file path if a CSV file is required. NB Keep this function call at the end of the script.  
# # write.csv(pathways_df, file = "C:/your/file/path/something/like/output_files/your_filename.csv")   

```

## Checks    
```{r checks of length for rename answer columns chunk, eval=FALSE}
length(column_names)
length(logV)
length(raw_question_numbers_int)
length(raw_question_numbers)
length(question_type_int)
length(question_type)
length(maqV)
length(maq_option_no)
length(question_numbers)

```

```{r checks for rename answer columns chunk, eval=FALSE}
# inspect intermediate objects
column_names # not useful as overwritten
logV
raw_question_numbers_int
raw_question_numbers
question_type_int
question_type
maqV
maq_option_no
question_numbers
```

```{r Check:  classes and types, eval=FALSE}
all_classes <- sapply(combined_df, class) %>% data.frame() %>% t() %>% data.frame() %>% rename(class1=1, class2=2)
all_types <- as.list(sapply(combined_df, typeof)) %>% data.frame() %>% t() %>% data.frame() %>% rename(type=1)
classes_and_types <- cbind(all_classes, all_types)
rm(all_classes, all_types)

classes_and_types %>% mk     

```




## Moved to source file 
```{r Create: constants and patterns for regex - will go into source file, eval=FALSE}
sortvec <- c("participant_id", "participant_label", "participant_status", 
        #     "obs_id", 
             "uuid", 
             "session_scheduled_time", "participant_start_time", "participant_end_time", "prompt_time", "record_time", "expiry_time",
                "duration_seconds_from_scheduled_to_completion_time", "duration_seconds_from_first_response_to_completion_time",
             "device_id", "device_manufacturer", "device_model", "device_last_used", "device_app_version", "device_app_update_date",
             "unanswered_status", "activity_version", "status", "triggering_logic_id", "triggering_logic_type", 
             "location", "n_miss_all")

q_type_exts <- c("saq", "maq", "num", "vas", "fft")

# extract Study number  
pattern1   <- "activity_response_" %R% repeated(DGT,4,5)          # extracts the *Study* no., not the activity no.
pattern1.1 <- "activity_response_" %R% repeated(DGT,4,5) %R% "_"  # used to remove unwanted chars from Study no.

# detect unwanted columns (to be removed)
pattern2 <- "_" %R% repeated("[a-z]", lo = 3, hi = 3) %R% "_question_" %R% "[0-9]"  
pattern2.1 <- DGT %R% optional(DGT) %R% "_maq_metadata_question_"

# extract activity number; this expression will extract 5- to 6-digit activity numbers.
pattern3 <- "activity_response_" %R% repeated(DGT,4,5) %R% "_" %R% repeated(DGT,5,6) %R% "_"  # extracts activity no.(+)
pattern3.1 <- "activity_response_" %R% repeated(DGT,4,5) %R% "_"                              # to remove unwanted chars

# extract numeric answer code to rewrite answer columns
pattern4 <- "\\{\"answer_id" %R% repeated(not_dgt(), lo = 2, hi = 28) %R% capture(DGT) %R% capture(optional(DGT)) %R% one_or_more(printable())

# extract question numbers  
pattern5 <- START %R% "x" %R% capture(repeated(DGT,0,2)) %R% "_" %R% repeated("[a-z]", lo = 3, hi = 3) %R% "_" %R% repeated(not_dgt(), lo = 0, hi = 18) %R% capture(repeated(DGT,0,2)) %R% one_or_more(printable())
pattern5.1 <- START %R% "x" %R% DGT %R% optional(DGT)   # 

# extract activity no. from df_name
pattern6 <- "_" %R% repeated(DGT, 5, 6) %R% "_df"   

# extract question type (SAQ, NUM, VAS, etc)
pattern7 <- START %R% "x" %R% repeated(DGT,1,2) %R% "_" %R% repeated("[a-z]",3,3) %R% "_" 
pattern7.1 <- repeated("[a-z]",3,3)    # used to acquire only the desired chars without surrounding chars

# extract MAQ option no.  
pattern8 <- "_maq_" %R% DGT %R% optional(DGT)

```

```{r Create: functions for use in rest of script - will go into source file, eval=FALSE}
number_extract_single2 <- function(x) {
  as.numeric(str_replace(x, pattern = pattern4, replacement = REF1))
  }

mk <- function(x) {
    kable(x) %>%kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
  }

```


## Deprecated    
```{r deprecated, eval=FALSE}
# combined_df %<>% 
#   mutate(participant_id = as.integer(participant_id)) %>% 
#   mutate(participant_status = as.integer(participant_status)) %>% 
#   mutate(obs_id = as.integer(obs_id)) %>% 
#   mutate(status = as.integer(status)) %>% 
#   mutate(triggering_logic_id = as.integer(triggering_logic_id)) %>% 
#   mutate(triggering_logic_type = as.integer(triggering_logic_type)) 

# test_df <- data.frame(a = c(6,7,8), b = c("a", "b", "c"))
# j <- 0
# for (j in 0:2)  {
#   j <- j + 1
# 
#   varname <- paste("constant_val", j, sep = "." )
#   assign(varname, 1:nrow(test_df))
# 
#   test_df %<>% mutate("constant_val.{j}" := eval(sym(varname)))
#   }

# for (df_name in df_names)  {
#   df_list[[df_name]] %<>% arrange(record_time)
#   activity_no <- str_extract(df_name, pattern = pattern6) %>% str_remove_all("df") %>% str_remove_all("_")
#   newvar <- paste("obs", activity_no, sep = "." )
#   df_list[[df_name]] %<>% mutate(newvar = row_number(), .before = uuid)
#  }

```

```{r Create: functions for preprocessing multiple answer questions, eval=FALSE}
# # put NA in 1340_Q19_MAQ
# test_pathways_baselines_df <- test_pathways_baselines_df %>%
#     mutate_at(vars(`1340_Q19_MAQ`), ~ na_if(., ""))             # NB mutate_at() may be depreceated by nnow; replace

# # create multiple cols for 1340_Q19_MAQ. First use str_split to create a matrix with one col for each answer, then make into df.
# diagnosed_conditions_mx <- str_split(string = test_pathways_baselines_df$`1340_Q19_MAQ`, pattern = " & ", simplify = TRUE)
# diagnosed_conditions_df <- as.data.frame(diagnosed_conditions_mx)
# 
# # Do I need a join to get the data in the right place? It seems not. 
# test_pathways_baselines_df <- bind_cols(test_pathways_baselines_df, diagnosed_conditions_df)
# 
# # rename columns. May need more code if someone has more than 6 answers. But I don't; the most answers anyone had was 6.  
# test_pathways_baselines_df <- rename(test_pathways_baselines_df, `1340_Q19_MAQ_1` = V1, `1340_Q19_MAQ_2` = V2, `1340_Q19_MAQ_3` = V3, `1340_Q19_MAQ_4` = V4, `1340_Q19_MAQ_5` = V5, `1340_Q19_MAQ_6` = V6)
# 
# # use str_replace to get numbers only, dump characters
# test_pathways_baselines_df <- test_pathways_baselines_df %>% 
#     mutate_at(vars(contains("1340_Q19_MAQ_")), number_extract_single)
# 
# # create col with concatenation of all Q19_MAQ cols
# test_pathways_baselines_df <- test_pathways_baselines_df %>% unite(`1340_Q19_MAQ_concat`, `1340_Q19_MAQ_1`:`1340_Q19_MAQ_6`, sep = ",", remove = FALSE)
# 
# # create binary cols for each concat answer
# pattern1 <- or1(c(",1,", ",1" %R% END, START %R% "1,"))
# pattern2 <- or1(c(",2,", ",2" %R% END, START %R% "2,"))
# pattern3 <- or1(c(",3,", ",3" %R% END, START %R% "3,"))
# pattern4 <- or1(c(",4,", ",4" %R% END, START %R% "4,"))
# pattern5 <- or1(c(",5,", ",5" %R% END, START %R% "5,"))
# pattern7 <- or1(c(",6,", ",6" %R% END, START %R% "6,"))
# pattern8 <- or1(c(",7,", ",7" %R% END, START %R% "7,"))
# pattern8 <- or1(c(",8,", ",8" %R% END, START %R% "8,"))
# pattern9 <- or1(c(",9,", ",9" %R% END, START %R% "9,"))
# pattern10 <- or1(c(",10,", ",10" %R% END, START %R% "10,"))
# 
# test_pathways_baselines_df <- test_pathways_baselines_df %>% 
#     mutate(`1340_Q19_MAQ_option1` = ifelse(str_detect(string = `1340_Q19_MAQ_concat`, pattern = pattern1), TRUE, FALSE)) %>%
#     mutate(`1340_Q19_MAQ_option2` = ifelse(str_detect(string = `1340_Q19_MAQ_concat`, pattern = pattern2), TRUE, FALSE)) %>%
#     mutate(`1340_Q19_MAQ_option3` = ifelse(str_detect(string = `1340_Q19_MAQ_concat`, pattern = pattern3), TRUE, FALSE)) %>% 
#      mutate(`1340_Q19_MAQ_option4` = ifelse(str_detect(string = `1340_Q19_MAQ_concat`, pattern = pattern4), TRUE, FALSE)) %>% 
#      mutate(`1340_Q19_MAQ_option5` = ifelse(str_detect(string = `1340_Q19_MAQ_concat`, pattern = pattern5), TRUE, FALSE)) %>% 
#      mutate(`1340_Q19_MAQ_option6` = ifelse(str_detect(string = `1340_Q19_MAQ_concat`, pattern = pattern7), TRUE, FALSE)) %>% 
#     mutate(`1340_Q19_MAQ_option7` = ifelse(str_detect(string = `1340_Q19_MAQ_concat`, pattern = pattern8), TRUE, FALSE)) %>% 
#     mutate(`1340_Q19_MAQ_option8` = ifelse(str_detect(string = `1340_Q19_MAQ_concat`, pattern = pattern8), TRUE, FALSE)) %>% 
#     mutate(`1340_Q19_MAQ_option9` = ifelse(str_detect(string = `1340_Q19_MAQ_concat`, pattern = pattern9), TRUE, FALSE)) %>% 
#     mutate(`1340_Q19_MAQ_option10` = ifelse(str_detect(string = `1340_Q19_MAQ_concat`, pattern = pattern10), TRUE, FALSE))
# 
# test_pathways_baselines_df <- test_pathways_baselines_df %>% 
#     mutate_at(vars(`1340_Q19_MAQ_1`:`1340_Q19_MAQ_6`), ~ factor(., levels = c(1:10), labels = c("Heart disease", "Other heart condition", "Blood clot thrombosis", "Asthma", "Hay fever", "Depression", "Anxiety", "Thyroid problems", "None of these", "Other"), exclude = NA))

```
