# names_combined_df

# [1] "obs_id"                                                  "session_scheduled_time"                                 

# [3] "a20908_q1_saq"                                           "a20908_q2_saq"                                          
# [5] "a20908_q3_saq"                                           "a20908_q4_saq"                                          
# [7] "a20908_q5_saq"                                           "a20908_q6_saq"                                          
# [9] "a20908_q7_saq"                                           "a20908_q8_saq"                                          
# [11] "a20908_q9_saq"                                           "a20908_q10_saq"                                         

# [13] "unanswered_status"                                       "participant_id"                                         
# [15] "participant_label"                                       "participant_start_time"                                 
# [17] "participant_end_time"                                    "participant_status"                                     
# [19] "device_id"                                               "device_manufacturer"                                    
# [21] "device_model"                                            "device_last_used"                                       
# [23] "device_app_version"                                      "device_app_update_date"                                 
# [25] "uuid"                                                    "activity_version"                                       
# [27] "prompt_time"                                             "record_time"                                            
# [29] "expiry_time"                                             "status"                                                 
# [31] "triggering_logic_id"                                     "triggering_logic_type"                                  
# [33] "duration_seconds_from_scheduled_to_completion_time"      "duration_seconds_from_first_response_to_completion_time"
# [35] "location"                                                

#                                                                "a20909_q1_vas"                                          
# [37] "a20909_q2_vas"                                           "a20909_q3_vas"                                          
# [39] "a20909_q4_vas"                                           "a20909_q5_vas"                                          
# [41] "a20909_q6_vas"                                           "a20909_q7_vas"                                          
# [43] "a20909_q8_vas"                                           "a20909_q9_vas"                                          
# [45] "a20909_q10_vas"                                          "a20909_q11_vas"                                         
# [47] "a20909_q12_vas"                                          "a20909_q13_vas"                                         
# [49] "a20909_q14_vas"                                          "a20909_q15_vas"                                         
# [51] "a20909_q16_vas"                                          "a20909_q17_vas"                                         
# [53] "a20909_q18_vas"                                          "a20909_q19_vas"                                         
# [55] "a20909_q20_vas"                                          "a20909_q21_vas"                                         
# [57] "a20909_q22_vas"                                          "a20909_q23_vas"                                         
# [59] "a20910_q1_saq"                                           "a20910_q2_num"                                          
# [61] "a20910_q3_num"                                           "a20910_q4_num"                                          
# [63] "a20910_q5_num"                                           "a20910_q6_num"                                          
# [65] "a20910_q7_num"                                           "a20910_q8_num"                                          
# [67] "a20910_q9_num"                                           "a20910_q10_maq_opt1"                                    
# [69] "a20910_q10_maq_opt2"                                     "a20910_q10_maq_opt3"                                    
# [71] "a20910_q10_maq_opt4"                                     "a20910_q10_maq_opt5"                                    
# [73] "a20910_q10_maq_opt6"                                     "a20910_q10_maq_opt7"                                    
# [75] "a20910_q10_maq_opt8"                                     "a20910_q10_maq_opt9"                                    
# [77] "a20910_q10_maq_opt10"                                    "a20910_q10_maq_opt11"                                   
# [79] "a20910_q10_maq_opt12"                                    "a20910_q10_maq_opt13"                                   
# [81] "a20910_q11_num"                                          "a20910_q12_num"                                         
# [83] "a20910_q13_saq"                                          "a20910_q14_num"                                         
# [85] "a20910_q15_num"                                          "a20910_q16_num"                                         
# [87] "a20910_q17_num"                                         


